/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterBookmarkFoldersResponse;
import net.troja.eve.esi.model.CharacterBookmarksResponse;
import net.troja.eve.esi.model.CorporationBookmarkFoldersResponse;
import net.troja.eve.esi.model.CorporationBookmarksResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BookmarksApi
 */
@Ignore
public class BookmarksApiTest {

    private final BookmarksApi api = new BookmarksApi();

    
    /**
     * List bookmarks
     *
     * A list of your character&#39;s personal bookmarks  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-bookmarks.read_character_bookmarks.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdBookmarksTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<CharacterBookmarksResponse> response = api.getCharactersCharacterIdBookmarks(characterId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    
    /**
     * List bookmark folders
     *
     * A list of your character&#39;s personal bookmark folders  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-bookmarks.read_character_bookmarks.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdBookmarksFoldersTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<CharacterBookmarkFoldersResponse> response = api.getCharactersCharacterIdBookmarksFolders(characterId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    
    /**
     * List corporation bookmarks
     *
     * A list of your corporation&#39;s bookmarks  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-bookmarks.read_corporation_bookmarks.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdBookmarksTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<CorporationBookmarksResponse> response = api.getCorporationsCorporationIdBookmarks(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    
    /**
     * List corporation bookmark folders
     *
     * A list of your corporation&#39;s bookmark folders  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-bookmarks.read_corporation_bookmarks.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdBookmarksFoldersTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<CorporationBookmarkFoldersResponse> response = api.getCorporationsCorporationIdBookmarksFolders(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    
}
