/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterAffiliationResponse;
import net.troja.eve.esi.model.CharacterBlueprintsResponse;
import net.troja.eve.esi.model.CharacterCorporationHistoryResponse;
import net.troja.eve.esi.model.CharacterFatigueResponse;
import net.troja.eve.esi.model.CharacterMedalsResponse;
import net.troja.eve.esi.model.CharacterNotificationsResponse;
import net.troja.eve.esi.model.CharacterPortraitResponse;
import net.troja.eve.esi.model.CharacterResearchAgentsResponse;
import net.troja.eve.esi.model.CharacterResponse;
import net.troja.eve.esi.model.CharacterRolesResponse;
import net.troja.eve.esi.model.CharacterStandingsResponse;
import net.troja.eve.esi.model.CharacterStatsResponse;
import net.troja.eve.esi.model.CharacterTitlesResponse;
import net.troja.eve.esi.model.NewContactNotificationsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CharacterApi
 */
@Ignore
public class CharacterApiTest {

    private final CharacterApi api = new CharacterApi();

    
    /**
     * Get character&#39;s public information
     *
     * Public information about a character  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        CharacterResponse response = api.getCharactersCharacterId(characterId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    
    /**
     * Get agents research
     *
     * Return a list of agents research information for a character. The formula for finding the current research points with an agent is: currentPoints &#x3D; remainderPoints + pointsPerDay * days(currentTime - researchStartDate)  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-characters.read_agents_research.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdAgentsResearchTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterResearchAgentsResponse> response = api.getCharactersCharacterIdAgentsResearch(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get blueprints
     *
     * Return a list of blueprints the character owns  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-characters.read_blueprints.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdBlueprintsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<CharacterBlueprintsResponse> response = api.getCharactersCharacterIdBlueprints(characterId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    
    /**
     * Get corporation history
     *
     * Get a list of all the corporations a character has been a member of  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdCorporationhistoryTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        List<CharacterCorporationHistoryResponse> response = api.getCharactersCharacterIdCorporationhistory(characterId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    
    /**
     * Get jump fatigue
     *
     * Return a character&#39;s jump activation and fatigue information  ---  This route is cached for up to 300 seconds  SSO Scope: esi-characters.read_fatigue.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdFatigueTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        CharacterFatigueResponse response = api.getCharactersCharacterIdFatigue(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get medals
     *
     * Return a list of medals the character has  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-characters.read_medals.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMedalsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterMedalsResponse> response = api.getCharactersCharacterIdMedals(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get character notifications
     *
     * Return character notifications  ---  This route is cached for up to 600 seconds  --- Warning: This route has an upgrade available  --- [Diff of the upcoming changes](https://esi.evetech.net/diff/latest/dev/#GET-/characters/{character_id}/notifications/)  SSO Scope: esi-characters.read_notifications.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdNotificationsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterNotificationsResponse> response = api.getCharactersCharacterIdNotifications(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get new contact notifications
     *
     * Return notifications about having been added to someone&#39;s contact list  ---  This route is cached for up to 600 seconds  SSO Scope: esi-characters.read_notifications.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdNotificationsContactsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<NewContactNotificationsResponse> response = api.getCharactersCharacterIdNotificationsContacts(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get character portraits
     *
     * Get portrait urls for a character  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdPortraitTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        CharacterPortraitResponse response = api.getCharactersCharacterIdPortrait(characterId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    
    /**
     * Get character corporation roles
     *
     * Returns a character&#39;s corporation roles  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-characters.read_corporation_roles.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdRolesTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        CharacterRolesResponse response = api.getCharactersCharacterIdRoles(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get standings
     *
     * Return character standings from agents, NPC corporations, and factions  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-characters.read_standings.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdStandingsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterStandingsResponse> response = api.getCharactersCharacterIdStandings(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Yearly aggregate stats
     *
     * Returns aggregate yearly stats for a character  ---  This route is cached for up to 86400 seconds  SSO Scope: esi-characterstats.read.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdStatsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterStatsResponse> response = api.getCharactersCharacterIdStats(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get character corporation titles
     *
     * Returns a character&#39;s titles  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-characters.read_titles.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdTitlesTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterTitlesResponse> response = api.getCharactersCharacterIdTitles(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Character affiliation
     *
     * Bulk lookup of character IDs to corporation, alliance and faction  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCharactersAffiliationTest() throws ApiException {
        List<Integer> characters = null;
        String datasource = null;
        List<CharacterAffiliationResponse> response = api.postCharactersAffiliation(characters, datasource);

        // TODO: test validations
    }
    
    /**
     * Calculate a CSPA charge cost
     *
     * Takes a source character ID in the url and a set of target character ID&#39;s in the body, returns a CSPA charge cost  ---   SSO Scope: esi-characters.read_contacts.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdCspaTest() throws ApiException {
        Integer characterId = null;
        List<Integer> characters = null;
        String datasource = null;
        String token = null;
        Float response = api.postCharactersCharacterIdCspa(characterId, characters, datasource, token);

        // TODO: test validations
    }
    
}
