/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterClonesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClonesApi
 */
@Ignore
public class ClonesApiTest {

    private final ClonesApi api = new ClonesApi();

    
    /**
     * Get clones
     *
     * A list of the character&#39;s clones  ---  This route is cached for up to 120 seconds  SSO Scope: esi-clones.read_clones.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdClonesTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        CharacterClonesResponse response = api.getCharactersCharacterIdClones(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get active implants
     *
     * Return implants on the active clone of a character  ---  This route is cached for up to 300 seconds  SSO Scope: esi-clones.read_implants.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdImplantsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<Integer> response = api.getCharactersCharacterIdImplants(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
}
