/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterFitting;
import net.troja.eve.esi.model.CharacterFittingResponse;
import net.troja.eve.esi.model.CharacterFittingsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FittingsApi
 */
@Ignore
public class FittingsApiTest {

    private final FittingsApi api = new FittingsApi();

    
    /**
     * Delete fitting
     *
     * Delete a fitting from a character  ---   SSO Scope: esi-fittings.write_fittings.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCharactersCharacterIdFittingsFittingIdTest() throws ApiException {
        Integer characterId = null;
        Integer fittingId = null;
        String datasource = null;
        String token = null;
        api.deleteCharactersCharacterIdFittingsFittingId(characterId, fittingId, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Get fittings
     *
     * Return fittings of a character  ---  This route is cached for up to 300 seconds  SSO Scope: esi-fittings.read_fittings.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdFittingsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterFittingsResponse> response = api.getCharactersCharacterIdFittings(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Create fitting
     *
     * Save a new fitting for a character  ---   SSO Scope: esi-fittings.write_fittings.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdFittingsTest() throws ApiException {
        Integer characterId = null;
        CharacterFitting fitting = null;
        String datasource = null;
        String token = null;
        CharacterFittingResponse response = api.postCharactersCharacterIdFittings(characterId, fitting, datasource, token);

        // TODO: test validations
    }
    
}
