/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.InsurancePricesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InsuranceApi
 */
@Ignore
public class InsuranceApiTest {

    private final InsuranceApi api = new InsuranceApi();

    
    /**
     * List insurance levels
     *
     * Return available insurance levels for all ship types  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInsurancePricesTest() throws ApiException {
        String acceptLanguage = null;
        String datasource = null;
        String ifNoneMatch = null;
        String language = null;
        List<InsurancePricesResponse> response = api.getInsurancePrices(acceptLanguage, datasource, ifNoneMatch, language);

        // TODO: test validations
    }
    
}
