/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterKillmailsResponse;
import net.troja.eve.esi.model.CorporationKillmailsResponse;
import net.troja.eve.esi.model.KillmailResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KillmailsApi
 */
@Ignore
public class KillmailsApiTest {

    private final KillmailsApi api = new KillmailsApi();

    
    /**
     * Get a character&#39;s recent kills and losses
     *
     * Return a list of a character&#39;s kills and losses going back 90 days  ---  This route is cached for up to 300 seconds  SSO Scope: esi-killmails.read_killmails.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdKillmailsRecentTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<CharacterKillmailsResponse> response = api.getCharactersCharacterIdKillmailsRecent(characterId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    
    /**
     * Get a corporation&#39;s recent kills and losses
     *
     * Get a list of a corporation&#39;s kills and losses going back 90 days  ---  This route is cached for up to 300 seconds  --- Requires one of the following EVE corporation role(s): Director  SSO Scope: esi-killmails.read_corporation_killmails.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdKillmailsRecentTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        String token = null;
        List<CorporationKillmailsResponse> response = api.getCorporationsCorporationIdKillmailsRecent(corporationId, datasource, ifNoneMatch, page, token);

        // TODO: test validations
    }
    
    /**
     * Get a single killmail
     *
     * Return a single killmail from its ID and hash  ---  This route is cached for up to 1209600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKillmailsKillmailIdKillmailHashTest() throws ApiException {
        String killmailHash = null;
        Integer killmailId = null;
        String datasource = null;
        String ifNoneMatch = null;
        KillmailResponse response = api.getKillmailsKillmailIdKillmailHash(killmailHash, killmailId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    
}
