/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterLoyaltyPointsResponse;
import net.troja.eve.esi.model.LoyaltyStoreOffersResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LoyaltyApi
 */
@Ignore
public class LoyaltyApiTest {

    private final LoyaltyApi api = new LoyaltyApi();

    
    /**
     * Get loyalty points
     *
     * Return a list of loyalty points for all corporations the character has worked for  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-characters.read_loyalty.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdLoyaltyPointsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterLoyaltyPointsResponse> response = api.getCharactersCharacterIdLoyaltyPoints(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * List loyalty store offers
     *
     * Return a list of offers from a specific corporation&#39;s loyalty store  ---  This route expires daily at 11:05
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLoyaltyStoresCorporationIdOffersTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        String ifNoneMatch = null;
        List<LoyaltyStoreOffersResponse> response = api.getLoyaltyStoresCorporationIdOffers(corporationId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    
}
