/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterMailinglistsResponse;
import net.troja.eve.esi.model.Mail;
import net.troja.eve.esi.model.MailHeadersResponse;
import net.troja.eve.esi.model.MailLabelSimple;
import net.troja.eve.esi.model.MailLabelsResponse;
import net.troja.eve.esi.model.MailMetaData;
import net.troja.eve.esi.model.MailResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MailApi
 */
@Ignore
public class MailApiTest {

    private final MailApi api = new MailApi();

    
    /**
     * Delete a mail label
     *
     * Delete a mail label  ---   SSO Scope: esi-mail.organize_mail.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCharactersCharacterIdMailLabelsLabelIdTest() throws ApiException {
        Integer characterId = null;
        Integer labelId = null;
        String datasource = null;
        String token = null;
        api.deleteCharactersCharacterIdMailLabelsLabelId(characterId, labelId, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Delete a mail
     *
     * Delete a mail  ---   SSO Scope: esi-mail.organize_mail.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCharactersCharacterIdMailMailIdTest() throws ApiException {
        Integer characterId = null;
        Integer mailId = null;
        String datasource = null;
        String token = null;
        api.deleteCharactersCharacterIdMailMailId(characterId, mailId, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Return mail headers
     *
     * Return the 50 most recent mail headers belonging to the character that match the query criteria. Queries can be filtered by label, and last_mail_id can be used to paginate backwards  ---  This route is cached for up to 30 seconds  SSO Scope: esi-mail.read_mail.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMailTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        List<Integer> labels = null;
        Integer lastMailId = null;
        String token = null;
        List<MailHeadersResponse> response = api.getCharactersCharacterIdMail(characterId, datasource, ifNoneMatch, labels, lastMailId, token);

        // TODO: test validations
    }
    
    /**
     * Get mail labels and unread counts
     *
     * Return a list of the users mail labels, unread counts for each label and a total unread count.  ---  This route is cached for up to 30 seconds  SSO Scope: esi-mail.read_mail.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMailLabelsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        MailLabelsResponse response = api.getCharactersCharacterIdMailLabels(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Return mailing list subscriptions
     *
     * Return all mailing lists that the character is subscribed to  ---  This route is cached for up to 120 seconds  SSO Scope: esi-mail.read_mail.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMailListsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterMailinglistsResponse> response = api.getCharactersCharacterIdMailLists(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Return a mail
     *
     * Return the contents of an EVE mail  ---  This route is cached for up to 30 seconds  SSO Scope: esi-mail.read_mail.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdMailMailIdTest() throws ApiException {
        Integer characterId = null;
        Integer mailId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        MailResponse response = api.getCharactersCharacterIdMailMailId(characterId, mailId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Send a new mail
     *
     * Create and send a new mail  ---   SSO Scope: esi-mail.send_mail.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdMailTest() throws ApiException {
        Integer characterId = null;
        Mail mail = null;
        String datasource = null;
        String token = null;
        Integer response = api.postCharactersCharacterIdMail(characterId, mail, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Create a mail label
     *
     * Create a mail label  ---   SSO Scope: esi-mail.organize_mail.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdMailLabelsTest() throws ApiException {
        Integer characterId = null;
        MailLabelSimple label = null;
        String datasource = null;
        String token = null;
        Integer response = api.postCharactersCharacterIdMailLabels(characterId, label, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Update metadata about a mail
     *
     * Update metadata about a mail  ---   SSO Scope: esi-mail.organize_mail.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putCharactersCharacterIdMailMailIdTest() throws ApiException {
        Integer characterId = null;
        MailMetaData contents = null;
        Integer mailId = null;
        String datasource = null;
        String token = null;
        api.putCharactersCharacterIdMailMailId(characterId, contents, mailId, datasource, token);

        // TODO: test validations
    }
    
}
