/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterAttributesResponse;
import net.troja.eve.esi.model.CharacterSkillqueueResponse;
import net.troja.eve.esi.model.CharacterSkillsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SkillsApi
 */
@Ignore
public class SkillsApiTest {

    private final SkillsApi api = new SkillsApi();

    
    /**
     * Get character attributes
     *
     * Return attributes of a character  ---  This route is cached for up to 3600 seconds  SSO Scope: esi-skills.read_skills.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdAttributesTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        CharacterAttributesResponse response = api.getCharactersCharacterIdAttributes(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get character&#39;s skill queue
     *
     * List the configured skill queue for the given character  ---  This route is cached for up to 120 seconds  SSO Scope: esi-skills.read_skillqueue.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdSkillqueueTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<CharacterSkillqueueResponse> response = api.getCharactersCharacterIdSkillqueue(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Get character skills
     *
     * List all trained skills for the given character  ---  This route is cached for up to 120 seconds  SSO Scope: esi-skills.read_skills.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdSkillsTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        CharacterSkillsResponse response = api.getCharactersCharacterIdSkills(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
}
