/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.SovereigntyCampaignsResponse;
import net.troja.eve.esi.model.SovereigntyMapResponse;
import net.troja.eve.esi.model.SovereigntyStructuresResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SovereigntyApi
 */
@Ignore
public class SovereigntyApiTest {

    private final SovereigntyApi api = new SovereigntyApi();

    
    /**
     * List sovereignty campaigns
     *
     * Shows sovereignty data for campaigns.  ---  This route is cached for up to 5 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSovereigntyCampaignsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        List<SovereigntyCampaignsResponse> response = api.getSovereigntyCampaigns(datasource, ifNoneMatch);

        // TODO: test validations
    }
    
    /**
     * List sovereignty of systems
     *
     * Shows sovereignty information for solar systems  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSovereigntyMapTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        List<SovereigntyMapResponse> response = api.getSovereigntyMap(datasource, ifNoneMatch);

        // TODO: test validations
    }
    
    /**
     * List sovereignty structures
     *
     * Shows sovereignty data for structures.  ---  This route is cached for up to 120 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSovereigntyStructuresTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        List<SovereigntyStructuresResponse> response = api.getSovereigntyStructures(datasource, ifNoneMatch);

        // TODO: test validations
    }
    
}
