/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.UiNewMail;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserInterfaceApi
 */
@Ignore
public class UserInterfaceApiTest {

    private final UserInterfaceApi api = new UserInterfaceApi();

    
    /**
     * Set Autopilot Waypoint
     *
     * Set a solar system as autopilot waypoint  ---   SSO Scope: esi-ui.write_waypoint.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUiAutopilotWaypointTest() throws ApiException {
        Boolean addToBeginning = null;
        Boolean clearOtherWaypoints = null;
        Long destinationId = null;
        String datasource = null;
        String token = null;
        api.postUiAutopilotWaypoint(addToBeginning, clearOtherWaypoints, destinationId, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Open Contract Window
     *
     * Open the contract window inside the client  ---   SSO Scope: esi-ui.open_window.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUiOpenwindowContractTest() throws ApiException {
        Integer contractId = null;
        String datasource = null;
        String token = null;
        api.postUiOpenwindowContract(contractId, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Open Information Window
     *
     * Open the information window for a character, corporation or alliance inside the client  ---   SSO Scope: esi-ui.open_window.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUiOpenwindowInformationTest() throws ApiException {
        Integer targetId = null;
        String datasource = null;
        String token = null;
        api.postUiOpenwindowInformation(targetId, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Open Market Details
     *
     * Open the market details window for a specific typeID inside the client  ---   SSO Scope: esi-ui.open_window.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUiOpenwindowMarketdetailsTest() throws ApiException {
        Integer typeId = null;
        String datasource = null;
        String token = null;
        api.postUiOpenwindowMarketdetails(typeId, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Open New Mail Window
     *
     * Open the New Mail window, according to settings from the request if applicable  ---   SSO Scope: esi-ui.open_window.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUiOpenwindowNewmailTest() throws ApiException {
        UiNewMail newMail = null;
        String datasource = null;
        String token = null;
        api.postUiOpenwindowNewmail(newMail, datasource, token);

        // TODO: test validations
    }
    
}
