/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.WarKillmailsResponse;
import net.troja.eve.esi.model.WarResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WarsApi
 */
@Ignore
public class WarsApiTest {

    private final WarsApi api = new WarsApi();

    
    /**
     * List wars
     *
     * Return a list of wars  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWarsTest() throws ApiException {
        String datasource = null;
        String ifNoneMatch = null;
        Integer maxWarId = null;
        List<Integer> response = api.getWars(datasource, ifNoneMatch, maxWarId);

        // TODO: test validations
    }
    
    /**
     * Get war information
     *
     * Return details about a war  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWarsWarIdTest() throws ApiException {
        Integer warId = null;
        String datasource = null;
        String ifNoneMatch = null;
        WarResponse response = api.getWarsWarId(warId, datasource, ifNoneMatch);

        // TODO: test validations
    }
    
    /**
     * List kills for a war
     *
     * Return a list of kills related to a war  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWarsWarIdKillmailsTest() throws ApiException {
        Integer warId = null;
        String datasource = null;
        String ifNoneMatch = null;
        Integer page = null;
        List<WarKillmailsResponse> response = api.getWarsWarIdKillmails(warId, datasource, ifNoneMatch, page);

        // TODO: test validations
    }
    
}
